#!/usr/bin/env ruby

@@starting_dir = Dir.pwd
require "#{File.dirname(File.realpath(__FILE__))}/config/initializers/rails_env"
%w(gems logging models).each do |initializer|
  require "#{RAILS_ROOT}/config/initializers/#{initializer}"
end

################################################

class SynchzorInterface < Object

  INTERFACE_COMMANDS = [
      "list",
      "add",
      "remove",
      "synch",
      "sync",
      "all",
      "reset",
      "remote_clean",
      "remote_reset",
      "help"
  ]

  def self.init
    @command = ARGV[0]
    if @command.nil?
      self.help
    elsif INTERFACE_COMMANDS.include?(@command)
      SynchzorInterface.send(@command)
    else
      puts "That command is not valid.  Try 'synchzor help' to learn more."
    end
  end

  def self.help
    file = File.open("#{RAILS_ROOT}/help.txt", "rb")
    contents = file.read
    puts contents
  end

  def self.list
    Synchzor.list
  end

  def self.add
    Synchzor.add
  end

  def self.remove
    Synchzor.remove
  end

  def self.synch
    Synchzor.synch
  end

  def self.sync
    self.synch
  end

  def self.all
    Synchzor.all
  end

  def self.reset
    Synchzor.delete_db
  end

  def self.remote_clean
    Synchzor.remote_clean
  end

  def self.remote_reset
    Synchzor.remote_clean
    Synchzor.synch
  end

end

################################################

SynchzorInterface.init